modLoader = "javafml" #mandatory
loaderVersion = "[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "blueeyecommons" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Blue-Eye Commons" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="TheOneWithBlueEyes" #optional
description = '''   '''
